spring.application.name=publicbackend
server.port=8080

spring.jpa.open-in-view=false

# OAuth2 Google - values injected from environment variables
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# Database - values injected from environment variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Spring scheme sesssion store
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
spring.session.timeout=30d

# CORS config
app.frontend-url=${FRONTEND_URL}

# Pushover notifications
app.pushover.api-token=${PUSHOVER_API_TOKEN}
app.pushover.user-key=${PUSHOVER_USER_KEY}

# ANTHROPIC
anthropic.apiKey=${ANTHROPIC_API_KEY}

# SAMTRAFIKEN
samtrafiken.api-key=${SAMTRAFIKEN_STATIC_API_KEY}
samtrafiken.gtfs-url=https://opendata.samtrafiken.se/gtfs/sl/sl.zip

